/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintenance;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author John
 */
public class Main extends javax.swing.JFrame {

    public static LinkedList<Maquina> maquinas = new LinkedList<>();
    public static Maquina machine;
    
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.inicializarComponentes();
    }
    
    private void inicializarComponentes(){
        File file = new File("Maquinas.dat");
        
        if(file.exists()){
            try{
                ObjectInputStream ois = new  ObjectInputStream(new FileInputStream("Maquinas.dat"));
                Main.maquinas = (LinkedList<Maquina>) ois.readObject();
                ois.close();
            }catch(IOException | ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        DefaultListModel model = new DefaultListModel();
        
        if(maquinas.isEmpty()){
            model.clear();
            listMaquinas.setModel(model);
        }else{
            this.RefrescarListaMaquina();
        }
        
        DefaultListCellRenderer cellRenderer = (DefaultListCellRenderer)listMaquinas.getCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants .CENTER);
        
        DefaultListCellRenderer cellRenderer1 = (DefaultListCellRenderer)listPreventivo.getCellRenderer();
        cellRenderer1.setHorizontalAlignment(SwingConstants .CENTER);
        
        DefaultListCellRenderer cellRenderer2 = (DefaultListCellRenderer)listPredictivo.getCellRenderer();
        cellRenderer2.setHorizontalAlignment(SwingConstants .CENTER);
        
        DefaultListCellRenderer cellRenderer3 = (DefaultListCellRenderer)listCorrectivo.getCellRenderer();
        cellRenderer3.setHorizontalAlignment(SwingConstants .CENTER);
    }
    
    public static void RefrescarListaMaquina(){
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for(Maquina m : Main.maquinas){
            model.addElement(m.getNombre());
        }
        listMaquinas.setModel(model);
    }
    
    public void RefrescarListaMantenimiento(){
        DefaultListModel modelPreventivo = new DefaultListModel();
        DefaultListModel modelPredictivo = new DefaultListModel();
        DefaultListModel modelCorrectivo = new DefaultListModel();
        
        modelPreventivo.clear();
        modelPredictivo.clear();
        modelCorrectivo.clear();
        
        for(Mantenimiento m : machine.getMantenimientos()){
            switch(m.getTipo()){
                case "Preventivo":
                    modelPreventivo.addElement(m.getNombre());
                    break;
                case "Predictivo":
                    modelPredictivo.addElement(m.getNombre());
                    break;
                case "Correctivo":
                    modelCorrectivo.addElement(m.getNombre());
                    break;
            }
        }
        listPreventivo.setModel(modelPreventivo);
        listPredictivo.setModel(modelPredictivo);
        listCorrectivo.setModel(modelCorrectivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        mainContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listMaquinas = new javax.swing.JList();
        jTextField6 = new javax.swing.JTextField();
        btnAgregarMaquinas = new javax.swing.JButton();
        btnEliminarMaquinas = new javax.swing.JButton();
        btnDetallesMaquinas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelImagen = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPreventivo = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listPredictivo = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        listCorrectivo = new javax.swing.JList();
        btnAgregarMantenimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software de Mantenimiento");

        jPanel1.setBackground(new java.awt.Color(132, 160, 222));

        listMaquinas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listMaquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listMaquinasMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(listMaquinas);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Lista de Máquinas");
        jTextField6.setEnabled(false);

        btnAgregarMaquinas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregarMaquinas.setText("Agregar");
        btnAgregarMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMaquinasActionPerformed(evt);
            }
        });

        btnEliminarMaquinas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliminarMaquinas.setText("Eliminar");
        btnEliminarMaquinas.setEnabled(false);
        btnEliminarMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMaquinasActionPerformed(evt);
            }
        });

        btnDetallesMaquinas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDetallesMaquinas.setText("Ver Detalles");
        btnDetallesMaquinas.setEnabled(false);
        btnDetallesMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesMaquinasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jTextField6))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetallesMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetallesMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jPanel2.setBackground(new java.awt.Color(119, 137, 193));

        panelImagen.setBackground(new java.awt.Color(255, 255, 255));
        panelImagen.setPreferredSize(new java.awt.Dimension(155, 155));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.setText("Nombre de maquina");
        txtNombre.setEnabled(false);

        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        txtDetalles.setText("Modelo:\nNo. Serie:\nFecha de Compra:\nFecha Fabricacion:\nMade in ");
        txtDetalles.setEnabled(false);
        jScrollPane1.setViewportView(txtDetalles);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Tipos de Mantenimiento");
        jTextField2.setEnabled(false);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Predictivo");
        jTextField3.setEnabled(false);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Preventivo");
        jTextField4.setEnabled(false);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Correctivo");
        jTextField5.setEnabled(false);

        listPreventivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listPreventivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPreventivoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listPreventivo);

        listPredictivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listPredictivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPredictivoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listPredictivo);

        listCorrectivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listCorrectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCorrectivoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listCorrectivo);

        btnAgregarMantenimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregarMantenimiento.setText("Agregar Nuevo Mantenimiento");
        btnAgregarMantenimiento.setEnabled(false);
        btnAgregarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnAgregarMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAgregarMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContainerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMaquinasActionPerformed
        AddMachine machine = new AddMachine(this, true);
        machine.setVisible(true);
    }//GEN-LAST:event_btnAgregarMaquinasActionPerformed

    private void btnDetallesMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesMaquinasActionPerformed
        for(Maquina m : Main.maquinas){
            if(m.getNombre().equals(listMaquinas.getSelectedValue().toString())){
                machine = m;
                break;
            }
        }
        
        this.LLenarDetalles();
        this.RefrescarListaMantenimiento();
        
        btnAgregarMantenimiento.setEnabled(true);
    }//GEN-LAST:event_btnDetallesMaquinasActionPerformed

    private void btnAgregarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMantenimientoActionPerformed
        AddMaintenance.pos = Main.maquinas.indexOf(machine);
        AddMaintenance maintenance = new AddMaintenance(this, true);
        maintenance.setVisible(true);
    }//GEN-LAST:event_btnAgregarMantenimientoActionPerformed

    private void listMaquinasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMaquinasMousePressed
        btnDetallesMaquinas.setEnabled(true);
        btnEliminarMaquinas.setEnabled(true);
    }//GEN-LAST:event_listMaquinasMousePressed

    private void listPreventivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPreventivoMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            for(Mantenimiento m : machine.getMantenimientos()){
                if(m.getNombre().equals(listPreventivo.getSelectedValue().toString())){
                    for(int i=0; i<m.getFechas().size(); i++){
                        System.out.println(m.getFechas().get(i));
                        System.out.println("Costo = " + m.getCosto());
                    }
                    System.out.println("Costo total = " + m.getCostoTotal());
                }
            }
        }
    }//GEN-LAST:event_listPreventivoMouseClicked

    private void listPredictivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPredictivoMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            for(Mantenimiento m : machine.getMantenimientos()){
                if(m.getNombre().equals(listPredictivo.getSelectedValue().toString())){
                    for(int i=0; i<m.getFechas().size(); i++){
                        System.out.println(m.getFechas().get(i));
                        System.out.println("Costo = " + m.getCosto());
                    }
                    System.out.println("Costo total = " + m.getCostoTotal());
                }
            }
        }
    }//GEN-LAST:event_listPredictivoMouseClicked

    private void listCorrectivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCorrectivoMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            for(Mantenimiento m : machine.getMantenimientos()){
                if(m.getNombre().equals(listCorrectivo.getSelectedValue().toString())){
                    for(int i=0; i<m.getFechas().size(); i++){
                        System.out.println(m.getFechas().get(i));
                        System.out.println("Costo = " + m.getCosto());
                    }
                    System.out.println("Costo total = " + m.getCostoTotal());
                }
            }
        }
    }//GEN-LAST:event_listCorrectivoMouseClicked

    private void btnEliminarMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMaquinasActionPerformed
        this.ResetScreen();
    }//GEN-LAST:event_btnEliminarMaquinasActionPerformed

    private void LLenarDetalles(){
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        txtNombre.setText(machine.getNombre());
        
        txtDetalles.setText(
                "Modelo: " + machine.getModelo() + "\n" + 
                "No. Serie: " + machine.getNoSerie()+ "\n" +
                "Fecha de Compra: " + dateFormat.format(machine.getFechaCompra())+ "\n" +
                "Fecha Fabricacion: " + dateFormat.format(machine.getFechaFabricacion()) + "\n" +
                "Made in " + machine.getLugarFabricacion()
                        );
        
        ImageIcon ico = new ImageIcon(machine.getImagen());
        Icon icono = new ImageIcon(ico.getImage().getScaledInstance(220, 180, Image.SCALE_DEFAULT));
        lblImagen.setIcon(icono);
        this.repaint();
    }
    
    private void ResetScreen(){
        txtNombre.setText("Nombre de Maquina");
        
        txtDetalles.setText(
                "Modelo: " + "\n" + 
                "No. Serie: " + "\n" +
                "Fecha de Compra: " + "\n" +
                "Fecha Fabricacion: " + "\n" +
                "Made in "
                        );
        
        lblImagen.setIcon(null);
        this.repaint();
        
        DefaultListModel modelPreventivo = new DefaultListModel();
        DefaultListModel modelPredictivo = new DefaultListModel();
        DefaultListModel modelCorrectivo = new DefaultListModel();
        
        modelPreventivo.clear();
        modelPredictivo.clear();
        modelCorrectivo.clear();
        
        listPreventivo.setModel(modelPreventivo);
        listPredictivo.setModel(modelPredictivo);
        listCorrectivo.setModel(modelCorrectivo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMantenimiento;
    private javax.swing.JButton btnAgregarMaquinas;
    private javax.swing.JButton btnDetallesMaquinas;
    private javax.swing.JButton btnEliminarMaquinas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JList listCorrectivo;
    private static javax.swing.JList listMaquinas;
    private javax.swing.JList listPredictivo;
    private javax.swing.JList listPreventivo;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
